- name: ArmorCode Release Gate
  uses: docker://public.ecr.aws/armor-code/armorcode-release-gate:latest
  with:
  product: 'RamyDemoApp1'
  subProduct: 'RamyRepoTest'
    env: prod
    armorcodeHost: https://app.armorcode.com
    mode: block            # or "monitor"
    armorcodeAPIToken: ${{ secrets.ARMORCODE_API_TOKEN }}
    githubToken: ${{ github.token }}       # or ${{ secrets.GITHUB_TOKEN }}
    additionalAQLFilters: ""               # optional


          env: 'Production'
          armorcodeHost: 'https://app.armorcode.com'
          mode: 'block'
          armorcodeAPIToken: ${{ secrets.ARMORCODE_API_TOKEN }}
          githubToken: ${{ github.token }}
          additionalAQLFilters: ""
