name: ArmorCode Release Gate
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  release_gate_check: # Update the job name as needed
    runs-on: ubuntu-latest
    permissions:
      checks: write     # For writing to the checks tab
      pull-requests: write  # For commenting on PRs
      contents: read    # For accessing repo content
    steps:  
      - name: Run ArmorCode Release Gate
        id: armorcode_gate
        uses: docker://public.ecr.aws/armor-code/armorcode-release-gate:latest
        with:
          product: 'RamyDemoApp1'
          subProduct: 'RamyRepoTest'
          env: 'Production'
          armorcodeHost: 'https://app.armorcode.com'
          mode: 'block'
          armorcodeAPIToken: ${{ d140c3d1-1072-4367-b97a-be803d9d146e }}
          githubToken: ${{ github.token }}
          additionalAQLFilters: ""
